// api/driver-stats.js - Driver statistics API endpoint (Updated after 2025 British GP)
export default function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'GET') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  // Driver statistics updated after 2025 British Grand Prix (Round 12)
  const driverStats = {
    'Max Verstappen': {
      name: 'Max Verstappen',
      number: 1,
      country: 'Netherlands',
      countryFlag: '🇳🇱',
      age: 27,
      birthdate: '1997-09-30',
      championships: 4,
      wins: 62,
      podiums: 104,
      poles: 41,
      fastestLaps: 33,
      careerPoints: 2965,
      debut: 'Australia 2015',
      team: 'Red Bull Racing',
      nickname: 'Mad Max',
      height: '1.81m',
      weight: '72kg'
    },
    'Lewis Hamilton': {
      name: 'Lewis Hamilton',
      number: 44,
      country: 'United Kingdom',
      countryFlag: '🇬🇧',
      age: 40,
      birthdate: '1985-01-07',
      championships: 7,
      wins: 105,
      podiums: 203,
      poles: 104,
      fastestLaps: 67,
      careerPoints: 4864,
      debut: 'Australia 2007',
      team: 'Ferrari',
      nickname: 'Still I Rise',
      height: '1.74m',
      weight: '73kg'
    },
    'Charles Leclerc': {
      name: 'Charles Leclerc',
      number: 16,
      country: 'Monaco',
      countryFlag: '🇲🇨',
      age: 27,
      birthdate: '1997-10-16',
      championships: 0,
      wins: 8,
      podiums: 47,
      poles: 24,
      fastestLaps: 9,
      careerPoints: 1427,
      debut: 'Australia 2018',
      team: 'Ferrari',
      nickname: 'Il Predestinato',
      height: '1.80m',
      weight: '68kg'
    },
    'Lando Norris': {
      name: 'Lando Norris',
      number: 4,
      country: 'United Kingdom',
      countryFlag: '🇬🇧',
      age: 25,
      birthdate: '1999-11-13',
      championships: 0,
      wins: 9,
      podiums: 37,
      poles: 6,
      fastestLaps: 9,
      careerPoints: 1176,
      debut: 'Australia 2019',
      team: 'McLaren',
      height: '1.70m',
      weight: '68kg'
    },
    'George Russell': {
      name: 'George Russell',
      number: 63,
      country: 'United Kingdom',
      countryFlag: '🇬🇧',
      age: 26,
      birthdate: '1998-02-15',
      championships: 0,
      wins: 4,
      podiums: 20,
      poles: 3,
      fastestLaps: 8,
      careerPoints: 597,
      debut: 'Australia 2019',
      team: 'Mercedes',
      height: '1.85m',
      weight: '70kg'
    },
    'Fernando Alonso': {
      name: 'Fernando Alonso',
      number: 14,
      country: 'Spain',
      countryFlag: '🇪🇸',
      age: 43,
      birthdate: '1981-07-29',
      championships: 2,
      wins: 32,
      podiums: 98,
      poles: 22,
      fastestLaps: 23,
      careerPoints: 2216,
      debut: 'Australia 2001',
      team: 'Aston Martin',
      nickname: 'El Nano',
      height: '1.71m',
      weight: '68kg'
    },
    'Oscar Piastri': {
      name: 'Oscar Piastri',
      number: 81,
      country: 'Australia',
      countryFlag: '🇦🇺',
      age: 23,
      birthdate: '2001-04-06',
      championships: 0,
      wins: 7,
      podiums: 20,
      poles: 5,
      fastestLaps: 6,
      careerPoints: 839,
      debut: 'Bahrain 2023',
      team: 'McLaren',
      height: '1.83m',
      weight: '72kg'
    },
    'Carlos Sainz Jr.': {
      name: 'Carlos Sainz Jr.',
      number: 55,
      country: 'Spain',
      countryFlag: '🇪🇸',
      age: 30,
      birthdate: '1994-09-01',
      championships: 0,
      wins: 5,
      podiums: 27,
      poles: 5,
      fastestLaps: 6,
      careerPoints: 1189,
      debut: 'Australia 2015',
      team: 'Williams',
      nickname: 'Chili',
      height: '1.78m',
      weight: '68kg'
    },
    'Pierre Gasly': {
      name: 'Pierre Gasly',
      number: 10,
      country: 'France',
      countryFlag: '🇫🇷',
      age: 28,
      birthdate: '1996-02-07',
      championships: 0,
      wins: 1,
      podiums: 4,
      poles: 0,
      fastestLaps: 3,
      careerPoints: 406,
      debut: 'Malaysia 2017',
      team: 'Alpine',
      height: '1.77m',
      weight: '70kg'
    },
    'Alexander Albon': {
      name: 'Alexander Albon',
      number: 23,
      country: 'Thailand',
      countryFlag: '🇹🇭',
      age: 28,
      birthdate: '1996-03-23',
      championships: 0,
      wins: 0,
      podiums: 2,
      poles: 0,
      fastestLaps: 1,
      careerPoints: 250,
      debut: 'Australia 2019',
      team: 'Williams',
      height: '1.86m',
      weight: '74kg'
    },
    'Lance Stroll': {
      name: 'Lance Stroll',
      number: 18,
      country: 'Canada',
      countryFlag: '🇨🇦',
      age: 26,
      birthdate: '1998-10-29',
      championships: 0,
      wins: 0,
      podiums: 3,
      poles: 1,
      fastestLaps: 0,
      careerPoints: 263,
      debut: 'Australia 2017',
      team: 'Aston Martin',
      height: '1.82m',
      weight: '70kg'
    },
    'Yuki Tsunoda': {
      name: 'Yuki Tsunoda',
      number: 22,
      country: 'Japan',
      countryFlag: '🇯🇵',
      age: 24,
      birthdate: '2000-05-11',
      championships: 0,
      wins: 0,
      podiums: 0,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 87,
      debut: 'Bahrain 2021',
      team: 'Red Bull Racing',
      height: '1.59m',
      weight: '54kg'
    },
    'Nico Hülkenberg': {
      name: 'Nico Hülkenberg',
      number: 27,
      country: 'Germany',
      countryFlag: '🇩🇪',
      age: 37,
      birthdate: '1987-08-19',
      championships: 0,
      wins: 0,
      podiums: 1,
      poles: 1,
      fastestLaps: 2,
      careerPoints: 567,
      debut: 'Bahrain 2010',
      team: 'Kick Sauber',
      nickname: 'The Hulk',
      height: '1.84m',
      weight: '74kg'
    },
    'Esteban Ocon': {
      name: 'Esteban Ocon',
      number: 31,
      country: 'France',
      countryFlag: '🇫🇷',
      age: 28,
      birthdate: '1996-09-17',
      championships: 0,
      wins: 1,
      podiums: 3,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 418,
      debut: 'Belgium 2016',
      team: 'Haas',
      height: '1.86m',
      weight: '74kg'
    },
    'Kimi Antonelli': {
      name: 'Andrea Kimi Antonelli',
      number: 12,
      country: 'Italy',
      countryFlag: '🇮🇹',
      age: 18,
      birthdate: '2006-08-25',
      championships: 0,
      wins: 0,
      podiums: 2,
      poles: 1,
      fastestLaps: 1,
      careerPoints: 91,
      debut: 'Italy 2024',
      team: 'Mercedes',
      nickname: 'Baby Kimi',
      height: '1.74m',
      weight: '65kg'
    },
    'Oliver Bearman': {
      name: 'Oliver Bearman',
      number: 87,
      country: 'United Kingdom',
      countryFlag: '🇬🇧',
      age: 19,
      birthdate: '2005-05-08',
      championships: 0,
      wins: 0,
      podiums: 0,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 13,
      debut: 'Saudi Arabia 2024',
      team: 'Haas',
      height: '1.84m',
      weight: '70kg'
    },
    'Franco Colapinto': {
      name: 'Franco Colapinto',
      number: 7,
      country: 'Argentina',
      countryFlag: '🇦🇷',
      age: 22,
      birthdate: '2003-05-27',
      championships: 0,
      wins: 0,
      podiums: 0,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 0,
      debut: 'Emilia-Romagna 2025',
      team: 'Alpine',
      height: '1.73m',
      weight: '64kg'
    },
    'Gabriel Bortoleto': {
      name: 'Gabriel Bortoleto',
      number: 5,
      country: 'Brazil',
      countryFlag: '🇧🇷',
      age: 20,
      birthdate: '2004-10-14',
      championships: 0,
      wins: 0,
      podiums: 0,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 23,
      debut: 'Bahrain 2025',
      team: 'Kick Sauber',
      height: '1.77m',
      weight: '69kg'
    },
    'Isack Hadjar': {
      name: 'Isack Hadjar',
      number: 6,
      country: 'France',
      countryFlag: '🇫🇷',
      age: 20,
      birthdate: '2004-09-28',
      championships: 0,
      wins: 0,
      podiums: 0,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 16,
      debut: 'Bahrain 2025',
      team: 'RB',
      height: '1.75m',
      weight: '68kg'
    },
    'Liam Lawson': {
      name: 'Liam Lawson',
      number: 30,
      country: 'New Zealand',
      countryFlag: '🇳🇿',
      age: 22,
      birthdate: '2002-02-11',
      championships: 0,
      wins: 0,
      podiums: 0,
      poles: 0,
      fastestLaps: 0,
      careerPoints: 30,
      debut: 'Netherlands 2023',
      team: 'RB',
      height: '1.80m',
      weight: '72kg'
    }
  };

  try {
    res.status(200).json(driverStats);
  } catch (error) {
    console.error('Error in driver-stats API:', error);
    res.status(500).json({ 
      error: 'Failed to fetch driver statistics',
      message: error.message 
    });
  }
}